import { writePsd } from "https://esm.sh/ag-psd@27.0.0?bundle";
import JSZip from "https://esm.sh/jszip@3.10.1?bundle";

const $ = id => document.getElementById(id);
const state = { files: [], images: [], folderName: "Manhwa", cuts: [], zoom: 1, cover: null, watermark: null, exportKind: "split", includeCover: false, includeWatermark: false, busy: false };
const IMAGE_RE = /\.(png|jpe?g|webp|gif|bmp|avif)$/i;
const titles = {splitter:["IMAGE SPLITTER","ย่อยรูป Manhwa"],resizer:["WIDTH RESIZER","ปรับความกว้างภาพ"],cover:["COVER & WATERMARK","ภาพปก & Watermark"],export:["EXPORT MANAGER","Export Manager"]};

function log(message, type="ok") { const row=document.createElement("div");row.className="log-entry";const dot=document.createElement("span");dot.className="log-dot";if(type==="error")dot.style.background="#ff8f8f";if(type==="info")dot.style.background="#91b9ff";row.append(dot,document.createTextNode(message));$("log").prepend(row); }
let toastTimer;
function toast(message) { const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),3300); }
function bytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
function sortNatural(a,b){return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:"base"});}
function pageSwitch(page){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===`page-${page}`));$("crumb").textContent=titles[page][0];$("pageTitle").textContent=titles[page][1];}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>pageSwitch(b.dataset.page)));
$("clearAll").addEventListener("click",()=>{if(state.busy)return;if(!confirm("เริ่มงานใหม่และล้างรายการภาพที่เลือกไว้หรือไม่?"))return;state.files=[];state.images=[];state.cuts=[];state.folderName="Manhwa";renderAll();log("เริ่ม Workspace ใหม่","info");});
function getFolderName(fileList){const p=fileList[0]?.webkitRelativePath||"";return p.split("/")[0]||"Manhwa";}
async function loadFiles(fileList){const files=Array.from(fileList).filter(f=>IMAGE_RE.test(f.name)).sort(sortNatural);if(!files.length){toast("ไม่พบไฟล์ภาพในโฟลเดอร์ที่เลือก");return;}state.files=files;state.folderName=getFolderName(files);state.images=[];state.cuts=[];setProgress(0,`กำลังอ่านภาพ 0/${files.length}`);$("progressWrap").hidden=false;log(`เริ่มอ่าน ${files.length} ภาพจาก ${state.folderName}`,"info");for(let i=0;i<files.length;i++){try{const img=await loadImage(files[i]);state.images.push({file:files[i],name:files[i].name,width:img.naturalWidth,height:img.naturalHeight,src:URL.createObjectURL(files[i]),img});}catch(e){log(`อ่านภาพไม่สำเร็จ: ${files[i].name}`,"error");}setProgress(Math.round((i+1)/files.length*100),`กำลังอ่านภาพ ${i+1}/${files.length}`);}if(!state.images.length){toast("ไม่สามารถเปิดไฟล์ภาพเหล่านี้ได้");return;}state.images.sort((a,b)=>sortNatural(a.file,b.file));state.cuts=makeCuts(Number($("splitHeight").value)||5000);renderAll();$("progressWrap").hidden=true;log(`อ่านภาพสำเร็จ ${state.images.length} ไฟล์ · สูงรวม ${fmt(state.totalHeight)} px`);toast(`โหลดภาพ ${state.images.length} ไฟล์เรียบร้อย`);}
function loadImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("invalid image"));img.src=url;});}
$("folderInput").addEventListener("change",e=>loadFiles(e.target.files));
$("resizeFolderInput").addEventListener("change",e=>loadFiles(e.target.files));
function fmt(n){return Number(n||0).toLocaleString("en-US");}
Object.defineProperty(state,"totalHeight",{get(){return state.images.reduce((n,i)=>n+i.height,0);}});
Object.defineProperty(state,"maxWidth",{get(){return state.images.reduce((n,i)=>Math.max(n,i.width),0);}});
function makeCuts(step){if(!state.totalHeight||step<=0)return[];const a=[];for(let y=step;y<state.totalHeight;y+=step)a.push(y);return a;}
$("generateCuts").addEventListener("click",()=>{if(!state.images.length)return toast("เลือกโฟลเดอร์ภาพก่อน");const step=Number($("splitHeight").value);if(!Number.isFinite(step)||step<100)return toast("ระยะเส้นแบ่งต้องไม่น้อยกว่า 100 px");state.cuts=makeCuts(step);renderSplitter();toast(`สร้างเส้นแบ่ง ${state.cuts.length} เส้น`);log(`สร้างเส้นแบ่งทุก ${step}px จำนวน ${state.cuts.length} เส้น`);});
$("addCut").addEventListener("click",()=>{if(!state.totalHeight)return toast("เลือกโฟลเดอร์ภาพก่อน");const y=Math.min(state.totalHeight-1,Math.max(1,Math.round(state.totalHeight/2)));state.cuts.push(y);state.cuts.sort((a,b)=>a-b);renderSplitter();});
$("zoomIn").addEventListener("click",()=>{state.zoom=Math.min(2.5,state.zoom+.1);renderSplitter();});
$("zoomOut").addEventListener("click",()=>{state.zoom=Math.max(.3,state.zoom-.1);renderSplitter();});
function renderAll(){renderHeader();renderSplitter();renderImageList();renderResizeTable();renderExportSummary();}
function renderHeader(){$("fileCount").textContent=state.images.length?`${state.images.length} ภาพ · ${state.folderName}`:"ยังไม่ได้เลือกโฟลเดอร์";$("sourceFolderName").textContent=state.images.length?state.folderName:"ยังไม่มีโฟลเดอร์";$("resizeFolderName").textContent=state.images.length?state.folderName:"เลือกโฟลเดอร์เพื่ออ่านขนาดภาพ";$("resizeTotal").textContent=`${state.images.length} ภาพ`;$("dimensions").textContent=state.images.length?`${fmt(state.maxWidth)} px max width × ${fmt(state.totalHeight)} px total height`:"—";$("totalHeight").textContent=state.images.length?`${fmt(state.totalHeight)} px`:"—";$("pieceEstimate").textContent=state.images.length?`${state.cuts.length+1} ชิ้น`:"—";$("cutCount").textContent=`${state.cuts.length} เส้นแบ่ง`;}
function renderSplitter(){renderHeader();$("emptyPreview").hidden=!!state.images.length;$("longPreview").hidden=!state.images.length;$("zoomLabel").textContent=`${Math.round(state.zoom*100)}%`;if(!state.images.length)return;const content=$("longContent");content.replaceChildren();content.style.width=`${Math.min(100,state.zoom*100)}%`;for(const item of state.images){const img=document.createElement("img");img.className="source-img";img.src=item.src;img.alt=item.name;img.title=`${item.name} · ${item.width}×${item.height}`;content.append(img);}const layer=$("cutLayer");layer.replaceChildren();const renderedHeight=content.getBoundingClientRect().height;layer.style.height=`${renderedHeight}px`;state.cuts.forEach((y,index)=>{const line=document.createElement("div");line.className="cut-line";line.style.top=`${y/state.totalHeight*renderedHeight}px`;const label=document.createElement("span");label.className="cut-label";label.textContent=`${fmt(y)} px`;const del=document.createElement("button");del.className="cut-delete";del.type="button";del.textContent="×";del.title="ลบเส้นแบ่ง";del.addEventListener("click",e=>{e.stopPropagation();state.cuts.splice(index,1);renderSplitter();});label.append(del);line.append(label);let startY=0,startCut=0;line.addEventListener("pointerdown",e=>{if(e.target===del)return;startY=e.clientY;startCut=state.cuts[index];line.setPointerCapture(e.pointerId);});line.addEventListener("pointermove",e=>{if(!line.hasPointerCapture(e.pointerId))return;const dy=(e.clientY-startY)*state.totalHeight/renderedHeight;state.cuts[index]=Math.round(Math.max(1,Math.min(state.totalHeight-1,startCut+dy)));state.cuts.sort((a,b)=>a-b);line.style.top=`${state.cuts[index]/state.totalHeight*renderedHeight}px`;label.firstChild.textContent=`${fmt(state.cuts[index])} px`;});line.addEventListener("pointerup",()=>{renderSplitter();});layer.append(line);});}
function renderImageList(){const list=$("imageList");list.replaceChildren();if(!state.images.length){list.innerHTML='<div class="muted empty-small">ไฟล์ภาพจะแสดงที่นี่</div>';return;}state.images.forEach((im,i)=>{const row=document.createElement("div");row.className="image-row";const thumb=document.createElement("img");thumb.className="image-thumb";thumb.src=im.src;const meta=document.createElement("div");meta.className="image-meta";const name=document.createElement("strong");name.textContent=`${String(i+1).padStart(3,"0")} · ${im.name}`;const detail=document.createElement("small");detail.textContent=`${im.width} × ${im.height} · ${bytes(im.file.size)}`;meta.append(name,detail);row.append(thumb,meta);list.append(row);});}
function renderResizeTable(){const tbody=$("resizeRows");tbody.replaceChildren();if(!state.images.length){tbody.innerHTML='<tr><td colspan="4" class="muted center">ยังไม่มีข้อมูล</td></tr>';return;}const w=Math.max(1,Number($("targetWidth").value)||800);state.images.forEach(im=>{const tr=document.createElement("tr");const h=Math.max(1,Math.round(im.height*w/im.width));[im.name,`${im.width} × ${im.height}`,`${w} × ${h}`].forEach(t=>{const td=document.createElement("td");td.textContent=t;tr.append(td);});const status=document.createElement("td");status.className="good";status.textContent=im.width===w?"ขนาดตรงกัน":"พร้อมปรับ";tr.append(status);tbody.append(tr);});}
$("targetWidth").addEventListener("input",renderResizeTable);document.querySelectorAll(".preset").forEach(b=>b.addEventListener("click",()=>{$("targetWidth").value=b.dataset.width;document.querySelectorAll(".preset").forEach(x=>x.classList.toggle("active",x===b));renderResizeTable();}));
function renderExportSummary(){$("summarySource").textContent=state.images.length?state.folderName:"ยังไม่มีโฟลเดอร์";$("summaryOutput").textContent=state.folderName+({split:"_psd",resize:"_resize_psd",success:"_success_psd"}[state.exportKind]);$("summaryAssets").textContent=`Cover: ${state.cover?"พร้อม":"ไม่มี"} · Watermark: ${state.watermark?"พร้อม":"ไม่มี"}`;}
document.querySelectorAll(".export-option").forEach(b=>b.addEventListener("click",()=>{state.exportKind=b.dataset.export;document.querySelectorAll(".export-option").forEach(x=>x.classList.toggle("selected",x===b));renderExportSummary();}));
function previewAsset(file,target){if(!file)return;const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{target.replaceChildren(img);};img.src=url;}
$("coverInput").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{state.cover={file:f,img:await loadImage(f)};previewAsset(f,$("coverPreview"));renderExportSummary();log(`ตั้งค่าภาพปก: ${f.name}`);toast("เพิ่มภาพปกแล้ว");}catch{toast("ไม่สามารถเปิดไฟล์ภาพปกได้");}});
$("watermarkInput").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{state.watermark={file:f,img:await loadImage(f)};previewAsset(f,$("watermarkPreview"));renderExportSummary();log(`ตั้งค่า Watermark: ${f.name}`);toast("เพิ่ม Watermark แล้ว");}catch{toast("ไม่สามารถเปิดไฟล์ Watermark ได้");}});
$("watermarkOpacity").addEventListener("input",()=> $("opacityValue").textContent=`${$("watermarkOpacity").value}%`);
function setProgress(p,msg){$("progressBar").style.width=`${p}%`;$("progressText").textContent=msg;}
function canvasFor(w,h){const c=document.createElement("canvas");c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;}
function addImageLayer(children,name,img,w,h,opts={}){const c=canvasFor(w,h),ctx=c.getContext("2d",{alpha:true});if(opts.background){ctx.fillStyle=opts.background;ctx.fillRect(0,0,w,h);}if(img){ctx.globalAlpha=opts.opacity??1;let dw=w,dh=h,dx=0,dy=0;if(opts.fit==="contain"){const s=Math.min(w/img.naturalWidth,h/img.naturalHeight);dw=img.naturalWidth*s;dh=img.naturalHeight*s;dx=(w-dw)/2;dy=(h-dh)/2;}else if(opts.fit==="width"){dw=w;dh=img.naturalHeight*w/img.naturalWidth;}else if(opts.fit==="stretch"){dw=w;dh=h;}else{dw=w;dh=img.naturalHeight*w/img.naturalWidth;}if(opts.watermark){dw=w*.8;dh=img.naturalHeight*dw/img.naturalWidth;const pos=$("watermarkPosition").value;dx=pos==="left"?0:pos==="right"?w-dw:pos==="center"?(w-dw)/2:Math.random()*(w-dw);dy=(h-dh)/2;}ctx.drawImage(img,dx,dy,dw,dh);}children.push({name,canvas:c,opacity:1});}
function cropPiece(startY,endY){const h=endY-startY,w=state.maxWidth,c=canvasFor(w,h),ctx=c.getContext("2d");let y=0;for(const im of state.images){const top=y,bottom=y+im.height;const overlapTop=Math.max(startY,top),overlapBottom=Math.min(endY,bottom);if(overlapBottom>overlapTop){const sy=overlapTop-top,sh=overlapBottom-overlapTop;const dx=Math.floor((w-im.width)/2);ctx.drawImage(im.img,0,sy,im.width,sh,dx,overlapTop-startY,im.width,sh);}y=bottom;if(y>=endY)break;}return c;}
function cropSingle(im,targetW=null){const w=targetW||im.width,h=targetW?Math.max(1,Math.round(im.height*targetW/im.width)):im.height,c=canvasFor(w,h);c.getContext("2d").drawImage(im.img,0,0,w,h);return c;}
function psdBuffer(children,w,h){const result=writePsd({width:w,height:h,children},{generateThumbnail:true});return result instanceof Uint8Array?result:new Uint8Array(result);}
function addWatermarkLayer(children,w,h){if(!state.includeWatermark||!state.watermark)return;const c=canvasFor(w,h),ctx=c.getContext("2d");ctx.globalAlpha=Number($("watermarkOpacity").value)/100;const img=state.watermark.img,dw=w*.8,dh=img.naturalHeight*dw/img.naturalWidth;let x;const p=$("watermarkPosition").value;x=p==="left"?0:p==="right"?w-dw:p==="center"?(w-dw)/2:Math.random()*Math.max(0,w-dw);ctx.drawImage(img,x,(h-dh)/2,dw,dh);children.push({name:"Watermark",canvas:c});}
function addCoverLayer(children,w,h){if(!state.includeCover||!state.cover)return;addImageLayer(children,"Cover Image",state.cover.img,w,h,{fit:$("coverFit").value});}
function makePsdBytes(mainCanvas,name,w,h,isFirst,isLast){const children=[{name:"Main Image",canvas:mainCanvas}];if(isFirst||isLast)addCoverLayer(children,w,h);addWatermarkLayer(children,w,h);return psdBuffer(children,w,h);}
async function buildZip(kind,opts={}){if(state.busy)return;if(!state.images.length)throw new Error("กรุณาเลือกโฟลเดอร์ภาพก่อน");state.busy=true;const zip=new JSZip(),outSuffix={split:"_psd",resize:"_resize_psd",success:"_success_psd"}[kind],outFolder=`${state.folderName}${outSuffix}`,out=zip.folder(outFolder),og=zip.folder("OG-Original");state.files.forEach(f=>og.file(f.webkitRelativePath?.split("/").slice(1).join("/")||f.name,f));let tasks=[];if(kind==="split"){const boundaries=[0,...state.cuts,state.totalHeight];for(let i=0;i<boundaries.length-1;i++)tasks.push({name:`${String(i+1).padStart(3,"0")}.psd`,start:boundaries[i],end:boundaries[i+1]});}else{tasks=state.images.map((im,i)=>({name:`${String(i+1).padStart(3,"0")}.psd`,image:im,index:i}));}
  $("progressWrap").hidden=false;try{for(let i=0;i<tasks.length;i++){const t=tasks[i];let main,w,h;if(kind==="split"){main=cropPiece(t.start,t.end);w=main.width;h=main.height;}else{const target=kind==="resize"?Math.max(1,Number($("targetWidth").value)||800):null;main=cropSingle(t.image,target);w=main.width;h=main.height;}const isFirst=i===0,isLast=i===tasks.length-1;const buf=makePsdBytes(main,t.name,w,h,isFirst,isLast);out.file(t.name,buf);setProgress(Math.round((i+1)/tasks.length*90),`สร้าง PSD ${i+1}/${tasks.length}`);await new Promise(r=>setTimeout(r,0));}
    const note=`Manhwa Splitter Studio export\nSource folder: ${state.folderName}\nMode: ${kind}\nFiles: ${tasks.length}\nPSD layers: Main Image${state.includeCover&&state.cover?", Cover Image":""}${state.includeWatermark&&state.watermark?", Watermark":""}\nOriginal files are in OG-Original.\n`;zip.file("README-export.txt",note);setProgress(92,"กำลังบีบอัด ZIP…");const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:3}},meta=>setProgress(92+Math.round(meta.percent*.08),`กำลังบีบอัด ZIP ${Math.round(meta.percent)}%`));downloadBlob(blob,`${state.folderName}${outSuffix}.zip`);setProgress(100,"เสร็จสมบูรณ์");log(`Export สำเร็จ: ${state.folderName}${outSuffix}.zip · ${tasks.length} PSD`);toast("สร้าง ZIP เรียบร้อยแล้ว");return true;
  }finally{state.busy=false;setTimeout(()=>$("progressWrap").hidden=true,1600);}}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
let pendingKind="split";
function askExport(kind){pendingKind=kind;if(!state.images.length)return toast("กรุณาเลือกโฟลเดอร์ภาพก่อน");$("includeCover").checked=!!state.cover;$("includeWatermark").checked=!!state.watermark;$("dialogWarning").hidden=true;$("coverDialog").showModal();}
$("exportSplit").addEventListener("click",()=>askExport("split"));$("exportResize").addEventListener("click",()=>askExport("resize"));$("exportSelected").addEventListener("click",()=>askExport(state.exportKind));
$("confirmExport").addEventListener("click",async e=>{e.preventDefault();state.includeCover=$("includeCover").checked;state.includeWatermark=$("includeWatermark").checked;$("coverDialog").close();if(state.includeCover&&!state.cover){toast("เลือกใส่ภาพปก แต่ยังไม่ได้อัปโหลดภาพปก");pageSwitch("cover");return;}if(state.includeWatermark&&!state.watermark){toast("เลือกใส่ Watermark แต่ยังไม่ได้อัปโหลดไฟล์");pageSwitch("cover");return;}try{await buildZip(pendingKind);}catch(err){console.error(err);log(`Export ผิดพลาด: ${err.message||err}`,"error");toast(`Export ไม่สำเร็จ: ${err.message||"เกิดข้อผิดพลาด"}`);}});
$("exportOriginals").addEventListener("click",async()=>{if(!state.images.length)return toast("กรุณาเลือกโฟลเดอร์ภาพก่อน");const z=new JSZip(),og=z.folder("OG-Original");state.files.forEach(f=>og.file(f.webkitRelativePath?.split("/").slice(1).join("/")||f.name,f));const blob=await z.generateAsync({type:"blob"});downloadBlob(blob,`${state.folderName}_OG-Original.zip`);log("ดาวน์โหลดภาพ Original เรียบร้อย");});
$("clearLog").addEventListener("click",()=>$("log").replaceChildren());
window.addEventListener("resize",()=>{if(state.images.length)renderSplitter();});
renderAll();
